<?php

namespace Soluble\Normalist\Synthetic;


use Soluble\Db\Metadata\Source;
use Zend\Db\Adapter\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-02 at 11:56:37.
 */
class TableManagerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TableManager
     */
    protected $tableManager;


    /**
     *
     * @var \Zend\Db\Adapter\Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = \SolubleTestFactories::getDbAdapter();
        
        $cache   = \SolubleTestFactories::getCacheStorage();
        $metadata = new Source\MysqlISMetadata($this->adapter);
        //$metadata->setCache($cache);
        
        $this->tableManager = new TableManager($this->adapter);
        $this->tableManager->setMetadata($metadata);
        
        $this->table = $this->tableManager->table('product_category');        

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->adapter);
        unset($this->tableManager);
        unset($this->table);        
    }

    public function testGetDefaultMetadata()
    {
        $tm = new TableManager($this->adapter);
        $metadata = $tm->getMetadata();
        $this->assertInstanceOf('\Soluble\Db\Metadata\Source\AbstractSource', $metadata);
        
    }
    
    
    public function testTable()
    {
        $medias = $this->tableManager->table('media');
        $this->assertInstanceOf('\Soluble\Normalist\Synthetic\Table', $medias);
    }

    public function testTableThrowsInvalidArgumentException()
    {
        $this->setExpectedException("\Soluble\Normalist\Synthetic\Exception\InvalidArgumentException");
        $medias = $this->tableManager->table(array('cool'));
    }
    
    
    public function testTableThrowsTableNotFoundException()
    {
        $this->setExpectedException("\Soluble\Normalist\Synthetic\Exception\TableNotFoundException");
        $medias = $this->tableManager->table('table_that_does_not_exists');
    }

    public function testSelect()
    {
        $select = $this->tableManager->select('media');
        $this->assertInstanceOf('\Soluble\Db\Sql\Select', $select);
    }

    public function testUpdateThrowsColumnNotFoundException()
    {
        $this->setExpectedException('Soluble\Normalist\Synthetic\Exception\ColumnNotFoundException');
        $tm = $this->tableManager;
        $tm->update('media', array('cool' => 'test'), 'media_id = 1');
        
    }
    
    public function testInsertThrowsColumnNotFoundException()
    {
        $this->setExpectedException('Soluble\Normalist\Synthetic\Exception\ColumnNotFoundException');
        $tm = $this->tableManager;
        $tm->insert('media', array('cool' => 'test'));
        
    }
    

    public function testTransaction()
    {
        $tm = $this->tableManager;
        
        $legacy_mapping = "phpunit_tablemanager_transaction";
        $data = $this->createMediaRecordData($legacy_mapping);

        // Cleanup
        $medias = $tm->table('media');
        $media = $medias->findOneBy(array('legacy_mapping' => $legacy_mapping));
        if ($media) {
            $medias->delete($media['media_id']);
        }
        
        $tm->beginTransaction();
        
        $m = $medias->insert($data);
        $media_id_rollback = $m['media_id'];
        $this->assertTrue(is_numeric($media_id_rollback));
        $tm->rollback();
        
        $this->assertFalse($medias->find($media_id_rollback));
        
        $tm->beginTransaction();
        $m = $medias->insert($data);
        $media_id_commit = $m['media_id'];
        $this->assertTrue(is_numeric($media_id_commit));
        $tm->commit();
        
        $this->assertGreaterThanOrEqual($media_id_rollback, $media_id_commit);
        $this->assertTrue($medias->exists($media_id_commit));
        $medias->delete($media_id_commit);
    }

    public function testBeginTransactionThrowsTransactionException()
    {
        $driver = $this->adapter->getDriver();
        if ($driver instanceof \Zend\Db\Adapter\Driver\Mysqli\Mysqli) {
            // TEST with PDO_MYSQL instead
            $this->assertTrue(true);
            
            
        } else {
            $catched = false;
            $tm = $this->tableManager;
            $tm->beginTransaction();
            try {
                $tm->beginTransaction();
            } catch (Exception\TransactionException $e) {
                $catched = true;
                $tm->rollback();
            }
            $this->assertTrue($catched);
           
        }
    }    
    

    public function testCommitThrowsTransactionException()
    {
        $driver = $this->adapter->getDriver();
        
        if ($driver instanceof \Zend\Db\Adapter\Driver\Mysqli\Mysqli) {
            // testing PDO_MYSQL instead, Mysqli won't throw any exception
            // on invalid commit, rollback, start...
            $driver = 'PDO_Mysql';
            $adapter = \SolubleTestFactories::getDbAdapter(null, $driver);
            $tm = new TableManager($adapter);            
            
            // test than Mysqli does not throw exception
            $catched = false;
            try {
                $this->tableManager->commit();
            } catch (Exception\TransactionException $e) {
                $catched = true;
            }
            $this->assertFalse($catched, "Mysqli should not throw a transaction exception");
            
        } else {
            $tm = $this->tableManager;
        }
        
        $catched = false;
        
        
        try {
            $tm->commit();
        } catch (Exception\TransactionException $e) {
            $catched = true;
        }
        $this->assertTrue($catched, "Commit without starting a transaction should fail");

        $catched = false;
        try {
            $tm->rollback();
        } catch (Exception\TransactionException $e) {
            $catched = true;
        }
        $this->assertTrue($catched, "Rollback without starting a transaction should fail");

        $catched = false;
        try {
            $tm->beginTransaction();
            $tm->beginTransaction();
        } catch (Exception\TransactionException $e) {
            $tm->rollback();
            $catched = true;
        }
        $this->assertTrue($catched, "Double begin transaction should fail");
        
        
    }    
    
    public function testRollbackThrowsTransactionException()
    {
        $driver = $this->adapter->getDriver();
        if ($driver instanceof \Zend\Db\Adapter\Driver\Mysqli\Mysqli) {
            $this->assertTrue(true);
        } else {
        
            $catched = false;
            $tm = $this->tableManager;

            try {
                $tm->rollback();
            } catch (Exception\TransactionException $e) {
                $catched = true;
            }
            $this->assertTrue($catched);
        }
    }    

    
    public function testGetDbAdapter()
    {
        $adapter = $this->tableManager->getDbAdapter();
        $this->assertInstanceOf('\Zend\Db\Adapter\Adapter', $adapter);
        
    }

    public function testSetTablePrefix()
    {
        $tm = new TableManager($this->adapter);
        $ret = $tm->setTablePrefix('prefix_');
        $this->assertInstanceOf('\Soluble\Normalist\Synthetic\TableManager', $ret);
        
    }

    public function testGetTablePrefix()
    {
        $tm = new TableManager($this->adapter);
        $prefix = $tm->setTablePrefix('prefix_')->getTablePrefix();
        $this->assertEquals('prefix_', $prefix);
        
        
    }


    public function testGetPrefixedTable()
    {
        $tm = new TableManager($this->adapter);
        $prefixed = $tm->setTablePrefix('prefix_')->getPrefixedTable('cool');
        
        $this->assertEquals('prefix_cool', $prefixed);
        
    }

    /**
     * @todo   Implement testGetRelations().
     */
    public function testGetRelations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGetColumnsInformation().
     */
    public function testGetColumnsInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }



    public function testGetPrimaryKeys()
    {
        $pks = $this->tableManager->getPrimaryKeys('media');
        $this->assertInternalType('array', $pks);
        $this->assertEquals(1, count($pks));
        $this->assertEquals('media_id', $pks[0]);
    }

    public function testGetPrimaryKey()
    {
        $pk = $this->tableManager->getPrimaryKey('media');
        $this->assertInternalType('string', $pk);
        $this->assertEquals('media_id', $pk);
    }

    public function testGetMetadata()
    {
        $metadata = $this->tableManager->getMetadata();
        $this->assertInstanceOf('\Soluble\Db\Metadata\Source\AbstractSource', $metadata);
        
    }

    public function testGetMetadataThrowsUnsupportedFeatureException()
    {
        $this->setExpectedException('Soluble\Normalist\Synthetic\Exception\UnsupportedFeatureException');
        // Fake adapter
        
        $adapter = new Adapter(array(
            'driver' => 'Pdo_Sqlite',
            'database' => 'path/to/sqlite.db'            
        ));
        
        
        $tm = new TableManager($adapter); 
        $metadata = $tm->getMetadata();
        
        
    }    


    public function testSetMetadata()
    {
        $metadata = new Source\MysqlISMetadata($this->adapter);
        $tableManager = new TableManager($this->adapter);
        $ret = $tableManager->setMetadata($metadata);
        $this->assertInstanceOf('\Soluble\Normalist\Synthetic\TableManager', $ret);
    }
    
    /**
     * Return a media record suitable for database insertion
     * @return array
     */
    protected function createMediaRecordData($legacy_mapping=null)
    {
        $tm = $this->tableManager;
        $container = $tm->table('media_container')->findOneBy(array('reference' => 'PRODUCT_MEDIAS'));
        $container_id = $container['container_id'];
        $data  = array(
            'filename'  => 'phpunit_tablemanager.pdf',
            'filemtime' => 111000,
            'filesize'  => 5000,
            'container_id' => $container_id,
            'legacy_mapping' => $legacy_mapping
        );
        return $data;
    }    
    

}
