<?php

namespace Soluble\Normalist\Synthetic;


use Soluble\Db\Metadata\Source;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-02 at 11:56:37.
 */
class TableManagerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TableManager
     */
    protected $tableManager;


    /**
     *
     * @var \Zend\Db\Adapter\Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = \SolubleTestFactories::getDbAdapter();
        
        $cache   = \SolubleTestFactories::getCacheStorage();
        $metadata = new Source\MysqlISMetadata($this->adapter);
        //$metadata->setCache($cache);
        
        $this->tableManager = new TableManager($this->adapter);
        $this->tableManager->setMetadata($metadata);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testTable()
    {
        $medias = $this->tableManager->table('media');
        $this->assertInstanceOf('\Soluble\Normalist\Synthetic\Table', $medias);
    }

    public function testTableThrowsInvalidArgumentException()
    {
        $this->setExpectedException("\Soluble\Normalist\Synthetic\Exception\InvalidArgumentException");
        $medias = $this->tableManager->table(array('cool'));
    }
    
    
    public function testTableThrowsTableNotFoundException()
    {
        $this->setExpectedException("\Soluble\Normalist\Synthetic\Exception\TableNotFoundException");
        $medias = $this->tableManager->table('table_that_does_not_exists');
    }

    public function testSelect()
    {
        $select = $this->tableManager->select('media');
        $this->assertInstanceOf('\Soluble\Db\Sql\Select', $select);
    }

    /**
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testTransaction()
    {
        $tm = $this->tableManager;
        
        $legacy_mapping = "phpunit_tablemanager_transaction";
        $data = $this->createMediaRecordData($legacy_mapping);

        // Cleanup
        $medias = $tm->table('media');
        $media = $medias->findOneBy(array('legacy_mapping' => $legacy_mapping));
        if ($media) {
            $medias->delete($media['media_id']);
        }
        
        $tm->beginTransaction();
        
        $m = $medias->insert($data);
        $media_id_rollback = $m['media_id'];
        $this->assertTrue(is_numeric($media_id_rollback));
        $tm->rollback();
        
        $this->assertFalse($medias->find($media_id_rollback));
        
        $tm->beginTransaction();
        $m = $medias->insert($data);
        $media_id_commit = $m['media_id'];
        $this->assertTrue(is_numeric($media_id_commit));
        $tm->commit();
        
        $this->assertGreaterThanOrEqual($media_id_rollback, $media_id_commit);
        $this->assertTrue($medias->exists($media_id_commit));
        $medias->delete($media_id_commit);
    }

    public function testBeginTransactionThrowsTransactionException()
    {
        $catched = false;
        $tm = $this->tableManager;
        $tm->beginTransaction();
        try {
            $tm->beginTransaction();
        } catch (Exception\TransactionException $e) {
            $catched = true;
            $tm->rollback();
        }
        $this->assertTrue($catched);
    }    
    

    public function testCommitThrowsTransactionException()
    {
        $catched = false;
        $tm = $this->tableManager;
        
        try {
            $tm->commit();
        } catch (Exception\TransactionException $e) {
            $catched = true;
        }
        $this->assertTrue($catched);
    }    
    
    public function testRollbackThrowsTransactionException()
    {
        $catched = false;
        $tm = $this->tableManager;
        
        try {
            $tm->rollback();
        } catch (Exception\TransactionException $e) {
            $catched = true;
        }
        $this->assertTrue($catched);
    }    

    
    public function testGetDbAdapter()
    {
        $adapter = $this->tableManager->getDbAdapter();
        $this->assertInstanceOf('\Zend\Db\Adapter\Adapter', $adapter);
        
    }

    /**
     * @todo   Implement testSetTablePrefix().
     */
    public function testSetTablePrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGetTablePrefix().
     */
    public function testGetTablePrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGetPrefixedTable().
     */
    public function testGetPrefixedTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGetRelations().
     */
    public function testGetRelations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo   Implement testGetColumnsInformation().
     */
    public function testGetColumnsInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }



    public function testGetPrimaryKeys()
    {
        $pks = $this->tableManager->getPrimaryKeys('media');
        $this->assertInternalType('array', $pks);
        $this->assertEquals(1, count($pks));
        $this->assertEquals('media_id', $pks[0]);
    }

    public function testGetPrimaryKey()
    {
        $pk = $this->tableManager->getPrimaryKey('media');
        $this->assertInternalType('string', $pk);
        $this->assertEquals('media_id', $pk);
    }

    public function testGetMetadata()
    {
        $metadata = $this->tableManager->getMetadata();
        
        $this->assertInstanceOf('\Soluble\Db\Metadata\Source\AbstractSource', $metadata);
        
    }



    public function testSetMetadata()
    {
        $metadata = new Source\MysqlISMetadata($this->adapter);
        $tableManager = new TableManager($this->adapter);
        $ret = $tableManager->setMetadata($metadata);
        $this->assertInstanceOf('\Soluble\Normalist\Synthetic\TableManager', $ret);
    }
    
    /**
     * Return a media record suitable for database insertion
     * @return array
     */
    protected function createMediaRecordData($legacy_mapping=null)
    {
        $tm = $this->tableManager;
        $container = $tm->table('media_container')->findOneBy(array('reference' => 'PRODUCT_MEDIAS'));
        $container_id = $container['container_id'];
        $data  = array(
            'filename'  => 'phpunit_tablemanager.pdf',
            'filemtime' => 111000,
            'filesize'  => 5000,
            'container_id' => $container_id,
            'legacy_mapping' => $legacy_mapping
        );
        return $data;
    }    
    

}
