language: php

php:
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - printf "\n" | pecl install imagick
  - mkdir -p tests/tmp/cache 
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS phpunit_soluble_test_db;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then zcat tests/data/mysql/schema.sql.gz | mysql phpunit_soluble_test_db; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then zcat tests/data/mysql/data.sql.gz | mysql phpunit_soluble_test_db; fi"
  - composer install --prefer-dist --dev
  - sudo apt-get install jpegoptim libjpeg-progs optipng

script: ./bin/phpunit -v --configuration tests/travis/$DB.travis.xml

