language: php

php:
  - 5.3  
  - 5.4
  - 5.5
  - 5.6
  - hhvm  
  

matrix:
    include:
        - php: 5.3
          env: DB=mysql
        - php: 5.4
          env: DB=mysql
        - php: 5.5
          env: DB=mysql EXTERNAL=true
        - php: 5.6
          env: DB=mysql
    allow_failures:
        - php: hhvm

env:
    global:
        - EXTERNAL=false
    matrix:
        - DB=mysql

before_script:
  - if [[ $HHVM == false ]] ; then pecl install imagick ; fi 
  - mkdir -p tests/tmp/cache 
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - sh -c "pwd"
  - sh -c "which zcat"
  - sh -c "which php"
  - sh -c "php -m"
  - mysql -e "show databases;" -uroot
  - mysql -e "connect phpunit_soluble_test_db; show tables;" -uroot
  - composer install --no-interaction --prefer-dist --dev
  - mkdir build
  - mkdir -p build/logs
  - wget https://scrutinizer-ci.com/ocular.phar
  #- sudo apt-get install jpegoptim libjpeg-progs optipng

script: 
    
  - phpunit -v --configuration tests/config/phpunit.$DB.travis.xml 
  #- ./bin/phpcs --standard=PSR2 ./src --report=full --report-file=./tests/build/phpcs_report.txt
  #- php tests/coverage-checker.php "$HOME/belgattitude/solublecomponents/tests/build/logs/clover.xml" 50

after_script:
  - ls build/logs  
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - sh -c "which java"
  - sh -c "java -version"
  #- ./bin/coveralls -c=./coveralls.yml -v 
  
