language: php

php:
  - 5.4
  - 5.6
  - hhvm  
  
matrix:
    include:
        - php: 5.3
          env: EXTERNAL=false ADAPTER=mysqli
        - php: 5.5
          env: EXTERNAL=true ADAPTER=mysqli
        - php: 5.5
          env: EXTERNAL=false ADAPTER=pdo_mysql          
    allow_failures:
        - php: hhvm

env:
    global:
        - DB=mysql
        - EXTERNAL=false
    matrix:
        - ADAPTER=mysqli
        - ADAPTER=pdo_mysql

before_script:
  - if [[ $HHVM == false ]] ; then pecl install imagick ; fi 
  - mkdir -p tests/tmp/cache 
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpunit_soluble_test_db;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - if [[ "$DB" == "mysql" ]]; then zcat tests/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db; fi
  - sh -c "pwd"
  - sh -c "which zcat"
  - sh -c "which php"
  - if [[ $HHVM == false ]] ; then php --version; fi 
  - if [[ $HHVM == false ]] ; then php --modules; fi 
  - if [[ $HHVM == false ]] ; then php --info; fi 
  - if [[ $HHVM == false ]] ; then php -r 'echo ini_get("error_log") . "\n";'; fi
  - mysql -e "show databases;" -uroot
  - mysql -e "connect phpunit_soluble_test_db; show tables;" -uroot
  - composer install --no-interaction --prefer-dist --dev
  - mkdir build
  - mkdir -p build/logs
  #- sudo apt-get install jpegoptim libjpeg-progs optipng

script: 
    
  - phpunit -v --configuration tests/config/phpunit.$ADAPTER.travis.xml 
  #- ./bin/phpcs --standard=PSR2 ./src --report=full --report-file=./tests/build/phpcs_report.txt
  #- php tests/coverage-checker.php "$HOME/belgattitude/solublecomponents/tests/build/logs/clover.xml" 50

after_script:
  - if [[ $HHVM == false ]] ; then php -r 'echo readfile(ini_get("error_log")) . "\n";'; fi
  #- cat $TRAVIS_BUILD_DIR/config/config.ini.php  
  - ls build/logs  
  - if [[ $EXTERNAL == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $EXTERNAL == true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
  - sh -c "which java"
  - sh -c "java -version"
  #- ./bin/coveralls -c=./coveralls.yml -v 
  - php -r 'echo readfile(ini_get("error_log"));'
  - php --version
  - php --info
  - php -d error_log=`pwd`/log.txt -d display_errors=On "./vendor/phpunit/phpunit/phpunit" -v --debug tests/config/phpunit.mysqli.travis.xml 
  - cat log.txt
  
