language: php

php:
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS phpunit_test_db;'; fi"
  - composer install --prefer-dist --dev
  - sudo apt-get install jpegoptim libjpeg-progs optipng

script: ./bin/phpunit -v --configuration tests/travis/$DB.travis.xml

