<?php

namespace Soluble\Media;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-06 at 12:05:20.
 */
class BoxDimensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BoxDimension
     */
    protected $box;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->box = new BoxDimension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSetWidth()
    {
        $width = 10;
        $ret = $this->box->setWidth($width);
        $this->assertInstanceOf('Soluble\Media\BoxDimension', $ret);
    }


    public function testGetWidth()
    {
        $width=20;
        $this->box->setWidth(20);
        $this->assertEquals($width, $this->box->getWidth());
    }


    public function testSetHeight()
    {
        $height = 10;
        $ret = $this->box->setHeight($height);
        $this->assertInstanceOf('Soluble\Media\BoxDimension', $ret);
    }


    public function testGetHeight()
    {
        $height=20;
        $this->box->setHeight($height);
        $this->assertEquals($height, $this->box->getHeight());
    }
}
