<?php

namespace Soluble\FlexStore\Writer;

use Soluble\FlexStore\Source\Zend\SelectSource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-16 at 15:18:12.
 */
class CSVTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var CSV
	 */
	protected $csvWriter;

	/**
	 * @var SelectSource
	 */
	protected $source;

	/**
	 *
	 * @var \Zend\Db\Adapter\Adapter
	 */
	protected $adapter;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->adapter = \SolubleTestFactories::getDbAdapter();
		$select = new \Zend\Db\Sql\Select();
		$select->from('product_category_translation')->where("lang = 'fr'")->limit(50);
		$params = array(
			'adapter' => $this->adapter,
			'select' => $select
		);

		$this->source = new SelectSource($params);


		$this->csvWriter = new CSV();
		$this->csvWriter->setSource($this->source);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Soluble\FlexStore\Writer\CSV::getData
	 */
	public function testGetData() {
		
		$data = $this->csvWriter->getData();
		$this->assertInternalType('string', $data);
	}

	/**
	 * @covers Soluble\FlexStore\Writer\CSV::getData
	 */
	public function testGetDataWithOptions() {
		$this->csvWriter->setOptions(
				array(
					'field_separator' => CSV::SEPARATOR_TAB,
					'line_separator' => CSV::SEPARATOR_NEWLINE_UNIX,
					'charset' => 'ISO-8859-1'
					)
				);
		$data = $this->csvWriter->getData();
		$this->assertInternalType('string', $data);

	}
	
	/**
	 * @covers Soluble\FlexStore\Writer\CSV::getOptions
	 */
	public function testGetDataWithOptionsThrowsInvalidArgumentException() {
		$this->setExpectedException('Soluble\FlexStore\Exception\InvalidArgumentException');
		$this->csvWriter->setOptions(
				array(
					'rossssss' => 'line',
					)
				);

		
		$data = $this->csvWriter->getData();
	}
	

	/**
	 * @covers Soluble\FlexStore\Writer\CSV::send
	 * @todo   Implement testSend().
	 */
	public function testSend() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
